services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped
